services:
  authapi:
    build: .
    container_name: fastauth-rbac
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fastapi_auth
      # - DATABASE_URL=postgresql://admin:adminpass@db:5432/fastapi_auth
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  db:
    image: postgres:15
    container_name: fastauth-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fastapi_auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      - db


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - authapi
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
